### PR TITLE
Created the first level layout for the game.

### PR DESCRIPTION
**Pull request by pouzts**

### CODE REVIEW

**Review by hababa2 — APPROVED** [review]
luks gud

**Review by BMann-png — CHANGES_REQUESTED** [review]
In the split make it less uniform

**Review by hababa2 — CHANGES_REQUESTED** [review]
Needs:
- Lighting
- Starting safe room
- Ending safe room
- Hallway
- Crawling section
- Basic landscape outside
- Colliders for walls and ramps

**Review by BMann-png — APPROVED** [review]

**Review by hababa2 — APPROVED** [review]
Lighting
    Starting safe room
    Ending safe room
    Hallway
    Crawling section
    Basic landscape outside
    Colliders for walls and ramps

**Pull request merged**
